### ISSUE TITLE
Distro Specific Installs.

### ISSUE THREAD

**Issue by Unorthodocs** [Umkus/unsee.cc#7]
What's up man,

I've gone through the setup phase on a CentOS/w cPanel to try and get this up and running accordingly to no avail. I'm not really finished with my attempts as of yet. 

Just wanted to know if you have things in the making to have this setup to work on a range of distros. 

I appreciate any feedback. 

Thanks,

**Comment by Umkus** [comment]
If still relevant - check out this repo: https://github.com/unsee-cc/fig
It should let you easily deploy the thing locally.
