### ISSUE TITLE
  // , Error code: sec_error_expired_certificate

### ISSUE THREAD

**Issue by v6** [Umkus/unsee.cc#8]
// , I visited unsee.cc, and Firefox showed me an error, "This Connection is Untrusted". 

    unsee.cc uses an invalid security certificate. 
    
    The certificate expired on 08/16/2015 04:59 PM. 
    
    The current time is 08/16/2015 09:39 PM.

![selection_655](https://cloud.githubusercontent.com/assets/5750764/9298217/d9836ab2-445f-11e5-83fe-dd16de3bb266.png)

**Comment by Umkus** [comment]
Thanks, it was renewed shortly after.

**Comment by v6** [comment]
// , I ended up with a similar error on a pre-production system for which I was responsible. 

http://letsencrypt.org lets you set up auto-renewal, I think.

**Comment by Umkus** [comment]
Yeah, I plan to move to that next year.

**Comment by v6** [comment]
// , :+1:
