### ISSUE TITLE
  // ,  Redis server went away

### ISSUE THREAD

**Issue by v6** [Umkus/unsee.cc#9]
// , I got the following error when I clicked and dragged two screenshots to unsee.cc: 

Redis server went away

![selection_656](https://cloud.githubusercontent.com/assets/5750764/9298247/3b19a5f2-4460-11e5-8c3f-27909941e769.png)

**Comment by Umkus** [comment]
This happens when the redis server docker image is caught between restarts. It should be auto-restarted automatically within a minute.

**Comment by v6** [comment]
// , Have you considered using a Redis cluster?

**Comment by Umkus** [comment]
That would mean having more than one box. And since moving to S3 is planned I would rather not invest into current set up much.
